name: Deploy to Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 18.232.61.210 >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no ubuntu@18.232.61.210 'bash -s' << 'EOF'
        # Commands to execute on the remote server
        echo "Hello from GitHub Actions on 18.232.61.210"
        # Add more commands as needed
        EOF

