name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH key
      run: |
        mkdir -p /root/.ssh
        echo "$SSH_PRIVATE_KEY" > /root/.ssh/id_rsa
        chmod 600 /root/.ssh/id_rsa
        chmod 700 /root/.ssh

    - name: SSH into Server
      run: |
        ssh -o StrictHostKeyChecking=no -v -i /root/.ssh/id_rsa ec2-user@54.224.70.214 'bash -s' << EOF
        echo 'Hello from GitHub Actions'
        # Your other commands here
        EOF

