name: Server Action

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight
  workflow_dispatch:    # Allow manual triggering

jobs:
  perform-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use the secret you created

      - name: Run Server Action
        run: |
          # Use SSH to execute commands on the server with debugging output
          ssh -o StrictHostKeyChecking=no -v ec2-user@54.224.70.214 'bash -s' << EOF
          echo 'Hello from GitHub Actions'
          # Your other commands here
          EOF

