name: SSH into EC2 and Run Script

on:
  push:
    branches:
      - main

jobs:
  remote_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run remote script
        run: |
          # List of hostnames to check
          hosts=("example1.com" "example2.com" "example3.com")
          
          # Loop through the hosts and print their names
          for host in "${hosts[@]}"; do
            echo "Host: $host"
          done

