name: Deploy to Remote Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH agent
      run: |
        eval "$(ssh-agent -s)"
        ssh-add /root/.ssh/id_rsa

    - name: Deploy to Remote Server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@18.232.61.210 'bash -s' << EOF
        # Commands to execute on the remote server
        echo "Hello from GitHub Actions!"
        # Add more commands here if needed
        EOF

