name: Execute Tasks on Remote Server

on:
  push:
    branches:
      - main

jobs:
  execute_tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Run tasks on remote server
        run: |
          ssh ubuntu@18.232.61.210 'bash -s' < your-local-script.sh

