name: SSH into EC2 and Run Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run remote script
        run: |
          echo "${KNOWN_HOSTS}" > known_hosts
          chmod 600 known_hosts
          ssh -o UserKnownHostsFile=known_hosts ubuntu@18.232.61.210 'bash -s' < /home/runner/work/Day3-task/Day3-task/.github/scripts/your-local-script.sh
        env:
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}

