name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        cp .github/keys/* ~/.ssh/
        chmod 600 ~/.ssh/id_rsa
        chmod 644 ~/.ssh/id_rsa.pub
        chmod 644 ~/.ssh/authorized_keys

    - name: SSH into remote server and execute commands
      run: |
        ssh -o StrictHostKeyChecking=no -v ec2-user@54.224.70.214 'bash -s' << EOF
        echo 'Hello from GitHub Actions'
        # Your other commands here
        EOF

