name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Use SSH to execute commands on the server
      run: |
        ssh -o StrictHostKeyChecking=no -v ec2-user@54.224.70.214 'bash -s' << EOF
        cd /root/.ssh/
        echo 'Hello from GitHub Actions'
        # Your other commands here
        EOF
      shell: /usr/bin/bash -e {0}
      env:
        SSH_AUTH_SOCK: /tmp/ssh-XXXXXXNgVNTe/agent.1745
        SSH_AGENT_PID: 1746

