name: Check SSL Expiry
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check-ssl-expiry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run SSL Expiry Check and Notify Slack
        run: |
          # Use your SSL expiry check script here
          # Replace `YOUR_COMMAND_HERE` with the actual command
          echo "Running SSL Expiry Check"
          echo "Sending Slack Notification"
          curl -X POST -H "Content-type: application/json" --data '{"text":"SSL Expiry Alert"}' ${{ secrets.SLACK_WEBHOOK_URL }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

