name: Check SSL Expiry and Notify Slack

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check-ssl-expiry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run SSL Expiry Check and Notify Slack
        run: |
          echo "Running SSL Expiry Check"

          # Run your SSL expiry check script and capture its output
          ssl_expiry_result=$(node .github/scripts/ssl_expiry_check_script.js)

          # Iterate through the alerts and format the message
          formatted_message=""
          for item in $ssl_expiry_result; do
            domain=$(echo "$item" | jq -r '.domain')
            days=$(echo "$item" | jq -r '.daysUntilExpiry')
            formatted_message+="Domain: $domain\nDays Until Expiry: $days\n\n"
          done

          # Send Slack notification using the formatted message
          curl -X POST -H "Content-type: application/json" --data "{\"text\":\"$formatted_message\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

